### ISSUE TITLE
Suggest no aliases

### ISSUE THREAD

**Issue by jdhitsolutions** [ecsousa/PSColors#2]
The recommended best practice for PowerShell scripting and modules is not to use aliases. Even I was confused by `cvpa` and had to look it up.  Since your code doesn't have much in the way of comments, using full cmdlet names would be very helpful.

**Comment by ecsousa** [comment]
I've review the code, and changed Aliases to Cmdlets. Also, I've have put some comments on what PSColors is doing, and why.

Thank you for your contribution. I will be review the other issues.

This was done in commit 8cd16ef04011ff6bf21b353876b6c5863e1b3fbf.
