### ISSUE TITLE
Background color bug

### ISSUE THREAD

**Issue by jdhitsolutions** [ecsousa/PSColors#4]
When I import the module and clear the screen I get a black background as expected. But when I do a directory listing, part of the background reverts to the previous background color. And if I run clear-host (cls)  I'm back to my original background color.

**Comment by ecsousa** [comment]
Usually I set background color do Black on Console shortcut itself (or in ConEmu). But the fact is, it seems that conhost keeps on reverting Background/Foregorund colors. Trying to manually setting this configuration is really messing up console colors.

I removed the portion of code that was forcing background and foreground colors; PSColors will now respect you console configuration (commit 4fd898379388844945f1dbb5e952b3eea3e08dde).
